settings:
  APP_DISPLAY_NAME: Skiris       # Le nom complet sous l'icône
  PRODUCTION_APP_NAME: Skiris    # Le nom utilisé pour la prod
  APP_GROUP_IDENTIFIER: group.io.skiris
  BASE_BUNDLE_IDENTIFIER: io.skiris.messenger # Ou ton propre ID
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "colors/accent-color"
  # DEVELOPMENT_TEAM: 7J4U792NQT